config/routes.rb
Coverlist::Application.routes.draw do
  resources :books

  devise_for :users

  get 'about' => 'pages#about'

  root :to => 'pages#home'

  resources :users
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :description, :featured, :link, :score, :title, :cover


  validates :description, presence: true
  

  belongs_to :user
  blah blah blah

  # the like associations
  has_many :likes
  has_many :liking_users, :through => :likes, :source => :user 

  has_attached_file :cover #, styles: { medium: "450x300"}
end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :added

  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         #:recoverable, 
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :books

  # the like associations
  has_many :likes
  has_many :liked_books, :through => :likes, :source => :book 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

# GET /user/1/edit
  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_book.html.erb
<div class="row">
    <div class="span5 offset2">
        <%= link_to image_tag(book.cover), book %><br>
        <tr>
            <td><%= link_to "Buy", book.link %></td>
            <td><%= book.score %></td>
            <td><%= @likes %></td>
      </tr>
    </div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for(@book, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

    <%= f.input :cover, label: "Book cover" %>
    <%= f.input :title %>
    <%= f.input :author %>
    <%= f.input :description, as: :text, input_html: { rows:"3" } %>
    <%= f.input :link %>
    <%= f.input :score %>
    <%= f.input :featured %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<%= render @books %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="row">
  <div class="span6">
    <div class="cover">
      <%= image_tag @book.cover %>
    </div>
  </div>
  <div class="span6">
    <div class="book-info">
      <div class="well">
      <p>
        <b>Title:</b>
        <%= @book.title %>
      </p>
      <p>
        <b>Author:</b>
        <%= @book.author %>
      </p>
      <p>
        <b>Description:</b>
        <%= @book.description %>
      </p>
    </div>
      <table class="table">
        <td>
          <p>
            <b><%= link_to "Buy", @book.link %></b>
          </p>
        </td>
        <td>
          <p>
            <b>Smiley:</b>
            <%= @book.score %>
          </p>
        </td>
        <td>
          <p>Add</p>
        </td>
      </table>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="navbar">
	<div class="navbar-inner">
		<div class="nav-collapse collapse">
			<div class="container">
                    <ul class="nav">
                       <li>    
                            <%= link_to 'Home',  root_path %>
                        </li>
                        <li>    
                            <%= link_to 'About Coverlist',  about_path %>
                        </li>
                    </ul>
					<ul class="nav pull-right">
	                  <li>
						<small>made by <%= link_to "Dani", "http://www.danifankhauser.com/"%></small>
					</li>
					</ul>
                </div>
            </div>
        </div>
    </div>
		
	</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <%= link_to "Coverlist ", root_path, class: "brand" %>
                <ul class="nav pull-right">
                    
                    <% if user_signed_in? %> 

                        <li><%= link_to 'My account',  edit_user_registration_path %></li>
                        <li><%= link_to 'Log out',  destroy_user_session_path, :method => :delete %></li>
                    
                    <% else %>
                        <li><%= link_to 'Log in',  new_user_session_path %></li>
                    <% end %>
                </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Coverlist</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>
	<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<div class="row">
	<div class="span4"></div>
	<div class="span8">
	  	<p>
				<%= link_to "Coverlist", "http://www.coverlist.com"%>
				is a place where books are judged by their covers. 
			</p>
	</div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<%= link_to "Booooks", "/books" %>
<% else %>
	<div class="center hero-unit">
	<h1>Welcome to Coverlist.</h1>
	<p>
		Find your next book on
		<%= link_to "Coverlist", "http://www.twitter.com/coverlist"%>.
	</p>
	<p>
		<%= link_to "Sign up now", new_user_registration_path, class: "btn btn-large btn-primary" %>
	</p>
	</div>
<% end %>

app/views/users/show.html.erb
<p>user profile</p>

<%= @user.name %>